name: apk_updater
description: "Custom Apk Installer Package"
version: 0.0.1
homepage: https://github.com/amitjha329/apk_updater
repository: https://github.com/amitjha329/apk_updater

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.apk_updater
        pluginClass: Plugin
